### ISSUE TITLE
[BUG] User has no Password set

### ISSUE THREAD

**Issue by salihoglu87** [RocketChat/Rocket.Chat.Android#1143]
Hello,

i installed the 2.0.2 Version of Android App on to Samsung Galaxy Note 8 with Android 8.0.0
If i try to sign in to my chat, i recieve the message: "User has no password set".
If i do it with the old (legacy) app, it works. It also works in browser and other ways. 
Only Android App "Rocket.Chat" throws me this exeption. 

Rocket.Chat Server 0.63.3

**Comment by salihoglu87** [comment]
One more thing, it does not matter what you type into Password field, it allways throws "User has no password set" . Same by correct and false Password.

**Comment by rafaelks** [comment]
@salihoglu87 Where it says this message? After you press the login button?

**Comment by salihoglu87** [comment]
I type my username and password and then i press the login button.. it just says "User has no password set".. in browser, or in other "legacy" app there are no problems.. just in native android app.

**Comment by salihoglu87** [comment]
![screenshot_20180420-125538_rocketchat](https://user-images.githubusercontent.com/30071247/39133900-97557c3c-4715-11e8-8701-bb5a888ecaa1.jpg)

**Comment by salihoglu87** [comment]
![screenshot_20180420-125538_rocketchat](https://user-images.githubusercontent.com/30071247/39133999-ddb0c448-4715-11e8-8fdc-ccd6637203ad.jpg)

**Comment by rafaelks** [comment]
@salihoglu87 How do you login on the web without a password? 🤔

**Comment by salihoglu87** [comment]
@rafaelks 
i have a password :D and even i can login on the web, i can't login ion android app.. thats the problem...
Any Ideas?

**Comment by waterboo** [comment]
Version: 0.63.3 with LDAP auth active, and the following options:
Login Fallback: no
Merge existing users: yes
Keep user data in sync: yes
Sync avatar: no
Background sync: no
Testing with 3 users here it is what happened:
a) user1 with a previously defined local password before ldap auth was active, authenticating via ldap in browser ok, desktop app ok, android app ok (not legacy)
b) user2 and user3 created when ldap authenticated for the first time, were able to authenticate via browser, desktop app, but were not able to authenticate via android app (not legacy) because of this error "user has no password set".
c) user2 has changed password via browser and now is able to authenticate via android app with the locally defined password, not the ldap one. 
d) user2 and user3 with legacy android app everything works.

**Comment by salihoglu87** [comment]
@waterboo Thank you!
So it means, for a user with only LDAP Credentials it is not possible to use a Rocket.Chat native Android App.

**Comment by salihoglu87** [comment]
@rafaelks is there any solution yet or some workaround?

**Comment by rafaelks** [comment]
@salihoglu87 We'll be investigating it, will get back to you soon.

**Comment by rafaelks** [comment]
@salihoglu87 Right now, we're only going to LDAP if the username you typed isn't an email. We'll submit a fix with this very soon. 👍

**Comment by salihoglu87** [comment]
Thank you @rafaelks.

**Comment by rafaelks** [comment]
@salihoglu87 Bug was fixed by #1236. You can join our Beta program in Google Play to download the fix in 1 hour. 👍

**Comment by waterboo** [comment]
@rafaelks is there any public release schedule that one can use to see when it lands in production (app store) ? Thanks.

**Comment by rafaelks** [comment]
@waterboo Yes, you can download it in our Google Play already, version 2.1.0.
