### ISSUE TITLE
Change launcher icon background 

### ISSUE THREAD

**Issue by MariusVolkhart** [RocketChat/Rocket.Chat.Android#1160]
## Description

I'd like to change the launcher icon background from white to Rocket Chat blue. This is a completely subjective change. To _me_ it looks nicer in the adaptive icon world, but others may disagree. If this change is off-brand or undesired, I will not be offended 😃

Some samples of the change:
<img width="287" alt="screen shot 2018-04-22 at 13 46 12" src="https://user-images.githubusercontent.com/1709517/39098899-384008ea-4637-11e8-9a8b-5c4ebedfb5f1.png">
<img width="292" alt="screen shot 2018-04-22 at 13 45 59" src="https://user-images.githubusercontent.com/1709517/39098900-38504eee-4637-11e8-8f0a-c3d8db0d1463.png">
<img width="299" alt="screen shot 2018-04-22 at 13 45 46" src="https://user-images.githubusercontent.com/1709517/39098901-385e06ce-4637-11e8-90b2-388ff1f61eca.png">
<img width="252" alt="screen shot 2018-04-22 at 13 45 32" src="https://user-images.githubusercontent.com/1709517/39098902-386e0c40-4637-11e8-923b-47afe87aa7c5.png">
<img width="282" alt="screen shot 2018-04-22 at 13 42 21" src="https://user-images.githubusercontent.com/1709517/39098903-387da952-4637-11e8-971e-5f9735ddadec.png">
<img width="284" alt="screen shot 2018-04-22 at 13 42 10" src="https://user-images.githubusercontent.com/1709517/39098904-388da212-4637-11e8-89b6-b71465c93563.png">
<img width="287" alt="screen shot 2018-04-22 at 13 41 57" src="https://user-images.githubusercontent.com/1709517/39098905-389b4dc2-4637-11e8-8c29-aa6fef2235e8.png">
<img width="290" alt="screen shot 2018-04-22 at 13 41 45" src="https://user-images.githubusercontent.com/1709517/39098906-38acfe0a-4637-11e8-8a5f-d405edd3f0de.png">

**Comment by philipbrito** [comment]
Hi @MariusVolkhart, 

If you take a look from the history [here](https://github.com/RocketChat/Rocket.Chat.Android/commits/develop/app/src/main/ic_launcher-web.png), you'll see that the icon on version "2.0.0-alpha1" was as you suggested, but since it was off-brand we changed the background to white.

On the iOS app there is the possibility to define a custom icon launcher (@rafaelks can confirm it), but since I never saw it in the Android world, I don't know if it is a good idea to add this feature here.

**Comment by rafaelks** [comment]
@filipedelimabrito Yes, iOS allows it.
