### ISSUE TITLE
Copy message feature not working

### ISSUE THREAD

**Issue by brnbs** [RocketChat/Rocket.Chat.Android#118]
Rocket.Chat.Android version: 2.5.0 from Play Store
Android version: 6.0.1

When long pressing on a message and selecting Copy from the menu, the app says "Copied" but the clipboard content wont change.

**Comment by laggedHero** [comment]
Hello @brnbs. Your issue is about https://github.com/RocketChat/Rocket.Chat.Cordova (hint: this native Android app is not available in the Play Store yet).

The Cordova app depends on some changes in the main project (https://github.com/RocketChat/Rocket.Chat) code. Version `0.49.0-develop` already have a fix for this issue (copy).

The server will need to be updated. You can follow up https://github.com/RocketChat/Rocket.Chat to stay up to date.

(I'll close this issue, since it's not about this project).
