### ISSUE TITLE
[REQUEST] Downgrade minSdkVersion to 19

### ISSUE THREAD

**Issue by shahar3012** [RocketChat/Rocket.Chat.Android#1216]
## Description

Hi,

We've been using Rocket.Chat for a couple of years at our organization. Up until recently we only used Rocket.Chat's web app.
We are planning to deploy Rocket.Chat android app to devices running Android 4.4.4, but we encountered  a problem with downgrading the project to `minSdkVersion` 19.

The following steps were taken to downgrade the app so far:

1. Change `minSdkVersion` to 19 at `build.gradle`
2. Add the following code to `build.gradle`:
```gradle
android { 
  defaultConfig {
    vectorDrawables.useSupportLibrary = true
    multiDexEnabled true
  } 
}
```
3. Add the following code to RocketChatApplication.kt to enable MultiDex:
```kotlin
override fun attachBaseContext(base: Context?) {
	super.attachBaseContext(base)
	MultiDex.install(this)
}
```
4. Change `app:src` with `app:srcCompat` at every ImageView.
5. Remove each usage of ripple effect

Here is a link to our fork:
[MobTar/Rocket.Chat.Android](https://github.com/MobTar/Rocket.Chat.Android/tree/min-sdk-19)

---

The following step needs to be done in order to proceed with the downgrading:

1. `MessageService` class which extends `JobService`, is only supported from API level 21 and above - Needs to be replaced with other implementation that supports API level 19.

## Devices and Versions
Your Rocket.Chat.Android version: 2.0.4
Your Rocket.Chat Server version: 0.63.3

Mobile device model and OS version: Android 4.4.4

---

We'd like to know, is there a particular reason to support only API level 21 and above?

Do you know of any other steps needed to proceed with the downgrade process?

**This is very important to our organization and we would appreciate any help we can get.**

**Comment by Amirko28** [comment]
👍

**Comment by Sagi363** [comment]
+1

**Comment by philipbrito** [comment]
> We'd like to know, is there a particular reason to support only API level 21 and above?

Yes. Many features of the current app only works from the API level 21 (you had mentioned some of them). When we chose to support only API 21+ we take care of this cases. Lollipop + Marshmallow + Nougat (excluding the most recent Oreo) takes more than 3/4 of all APIs accordingly [this dashboard](https://developer.android.com/about/dashboards/). We planned to start supporting a version released four years ago (2014).

We know that there are 10.5% of KitKat devices worldwide, but since this number tends to down more and more and we need to ship important features the KitKat support is not in the plans right now.

As always, feel free to submit PR's addressing this issue.
