### ISSUE TITLE
[IMPROVEMENT] In members list toolbar title is update after the member list is loaded

### ISSUE THREAD

**Issue by divyanshub024** [RocketChat/Rocket.Chat.Android#1294]
## Description

Should have similar feature like pinned message and favourite messages.

![ezgif-5-b85e9d82ae](https://user-images.githubusercontent.com/16731434/40353282-bdbeaba8-5dce-11e8-9060-02695dcf775b.gif)

**Comment by philipbrito** [comment]
This happens because we first process the API request and then get the number of members to show in the toolbar. File list is working in the same way too.

What I'd like to see is it showing the total number of pinned messages, favorite messages and mentions that a channel/user has too.

What do you think?

**Comment by rafaelks** [comment]
@filipedelimabrito I think we can start the screen with the title (without the number) and then add the number to the title once the list is loaded.

**Comment by divyanshub024** [comment]
@rafaelks This is good idea.

**Comment by rafaelks** [comment]
This is fixed already.
