### ISSUE TITLE
Error in application

### ISSUE THREAD

**Issue by guptamonu4** [RocketChat/Rocket.Chat.Android#1295]
## Devices and Versions

Your Rocket.Chat.Android version: (e.g. 2.1.0)
Your Rocket.Chat Server version: (e.g. 0.63.1-develop)

Mobile device model and OS version: (e.g. "Nexus 7 - Android 6.0.1")

## Logs

![error](https://user-images.githubusercontent.com/6302632/40355541-4dbae2d0-5dd4-11e8-976f-b0b0b2d77edb.png)

**Comment by guptamonu4** [comment]
I just import the kotlin app.
i found 9 error in this

**Comment by divyanshub024** [comment]
@guptamonu4 Make sure that the android repository and the kotlin sdk have the same immediate parent directory.

**Comment by abdellahaski** [comment]
you're missing this step as I think : 
https://github.com/RocketChat/Rocket.Chat.Android#sdk-instructions

SDK Instructions:
This version requires the Kotlin SDK for Rocket.Chat. Clone the Kotlin SDK in by running git clone https://github.com/RocketChat/Rocket.Chat.Kotlin.SDK.git.   
First, a build is required for the SDK, so that required jar files are generated. Make sure that the android repository and the kotlin sdk have the same immediate parent directory. Change the current directory to Rocket.Chat.Android/app and run the build-sdk.sh which will result in creating of the required jar file core*.jar and common*.jar in Rocket.Chat.Android/app/libs,by the following steps in your terminal window:

```
cd Rocket.Chat.Android/app
./build-sdk.sh
```

**Comment by rafaelks** [comment]
Closing this one since it was resolved already, thank you guys for the help! 👍

**Comment by mahmodsallam** [comment]
should i put the Kotlin Sdk in the project ???
how can i make this ?? help please

**Comment by divyanshub024** [comment]
@mahmodsallam Suppose there is the folder called "Rocket.Chat". In that folder you are supposed to put the app/project ("Rocket.Chat.Android") and sdk("Rocket.Chat.kotlin.sdk").
