### ISSUE TITLE
[BUG] Read receipt is not synchronised correctly

### ISSUE THREAD

**Issue by ArchimedesFM** [RocketChat/Rocket.Chat.Android#1365]
## Description

The new read receipt is not synchronised correctly between Desktop / Web and Android-Client.

## Devices and Versions
Your Rocket.Chat.Android version: 2.4.0 - Build 2027
Your Rocket.Chat Server version: 0.65.1
OnePlus 3T with Android 8

## Steps to reproduce

I send a picture via android app to a private message. After my colleague red the new message the read receipt indicator got blue on the desktop / web version, but not in the android version. After some other new messages it still stays gray. As you can see in the screenshot it works well with normal messages - maybe it depends on the picture.

![screenshot_20180614-082024](https://user-images.githubusercontent.com/26709898/41395237-3d7db4a2-6fad-11e8-84dc-39e52ebba06f.jpg)

**Comment by rafaelks** [comment]
This one is suppose to be fixed by now.

**Comment by rockneverdies55** [comment]
I am still having this issue in version 3.2.0. Initially it shows the correct information. The next time I come back to the channel I see that the read receipt status icon has turned blue. However if I click on the icon to see the current read status (whom seen the message), it actually shows only me in the list correctly (matches what the web shows). Thus the icon color should have been still gray instead of blue.
