### ISSUE TITLE
Is there any documentation for Rocket chat android development ??

### ISSUE THREAD

**Issue by JerushaSMendonza** [RocketChat/Rocket.Chat.Android#1492]
## Devices and Versions

Your Rocket.Chat.Android version: (e.g. 2.1.0)
Your Rocket.Chat Server version: (e.g. 0.63.1-develop)

Mobile device model and OS version: (e.g. "Nexus 7 - Android 6.0.1")

**Comment by philipbrito** [comment]
Basically, since it is a Kotlin project, we are following the [Kotlin Coding Conventions](https://kotlinlang.org/docs/reference/coding-conventions.html) for the app development. But yes, we need to formalize it here by updating this [section](https://github.com/RocketChat/Rocket.Chat.Android#coding-style).

**Comment by philipbrito** [comment]
@JerushaSMendonza -> https://github.com/RocketChat/Rocket.Chat.Android/issues/1497
