### ISSUE TITLE
There isn't show count of unread messages for channels and private groups in Chats.

### ISSUE THREAD

**Issue by TheSergeX** [RocketChat/Rocket.Chat.Android#1564]
It would be cool to have icon with count unread messages as it already have for private messages.

Your Rocket.Chat.Android version: (2.5.1)

**Comment by philipbrito** [comment]
Hi @Sergei-vb Check out your "Notification Preferences" for the desired channels that you want to show a counter in the web app.

<img width="369" alt="screen shot 2018-07-31 at 08 54 19" src="https://user-images.githubusercontent.com/11776825/43458121-684bd1a2-949f-11e8-9242-684037546106.png">

I'm using the 2.5.1 version here and everything is fine.

![2018-07-31 08 56 58](https://user-images.githubusercontent.com/11776825/43458213-b7cb324a-949f-11e8-9ff7-fe2d127165f0.jpg)

**Comment by rafaelks** [comment]
@filipedelimabrito You're seeing mentions, not the actual number of unread messages. This setting is **super** confusing and I opened an issue for that yesterday: https://github.com/RocketChat/Rocket.Chat/issues/11609

@Sergei-vb There's actually a environment variable that you can set into your server to enable this counter... can you please look for that in our docs or contact the core repository in order to get that? Thank you!

**Comment by TheSergeX** [comment]
@rafaelks I have already found way resolve of the problem.  `/administration/general/unread count` ---> `all messages`
thx!

**Comment by rafaelks** [comment]
@Sergei-vb Great! 👏

**Comment by philipbrito** [comment]
Oops, I'm sorry. Happy that you found a solution!

**Comment by trialsin** [comment]
How to make that config for some group/user. Like when we've some broad cast group or when the director or president talk on group. I know the user sending the message can put @all or @here, but some users forget that. Would be nice if we can set for group/user that default is @all or @here

I mean that for all client types (mobile, desktop, etc.)
