### ISSUE TITLE
the app don't compile 

### ISSUE THREAD

**Issue by Mohamed-Salah-WealthLab** [RocketChat/Rocket.Chat.Android#1594]
## Logs

No value passed for parameter 'subscriptionId' |  
-- | --
No value passed for parameter 'archived' |  
No value passed for parameter 'roles' |  
Unresolved reference: Livechat |  
No value passed for parameter 'roles' |  
No value passed for parameter 'subscriptionId' |  
No value passed for parameter 'archived' |  
No value passed for parameter 'roles' |  
No value passed for parameter 'subscriptionId' |  
No value passed for parameter 'archived' |

**Comment by philipbrito** [comment]
Hi @AboSala7, application is building as you can see from the CI.

**Comment by Mohamed-Salah-WealthLab** [comment]
thanks but what is CI

**Comment by philipbrito** [comment]
CI stands for _Continuous Integration_. You can see it status (if the app is building or not) easily from the [README.md](https://github.com/RocketChat/Rocket.Chat.Android#rocketchat-android-native-application).

<img width="960" alt="screen shot 2018-08-14 at 08 26 36" src="https://user-images.githubusercontent.com/11776825/44089123-09909992-9f9c-11e8-870b-6a366241d30a.png">

So, be sure to follow the steps described in the same mentioned file in order to build the app.
