### ISSUE TITLE
[BUG] Messages rendering out of order

### ISSUE THREAD

**Issue by Pitstopper** [RocketChat/Rocket.Chat.Android#1677]
Your Rocket.Chat.Android version: 2.6.0 Build 2042 - 658cee9a - play
Mobile device model: Xiaomi Redmi 3
OS version: MIUI 9.6 (9.6.2.0) , Global Stable
Your Rocket.Chat Server version: 0.69.2

If you post a few messages in a row, the last one jumps over the first. This is not visible for others. It's only seen by someone who posts a message.

![img_20180913_095750](https://user-images.githubusercontent.com/18574776/45472031-a42a7700-b73b-11e8-8ecb-93006baeef2d.png)

**Comment by antgel** [comment]
Nobody working on this? It's a pretty sad UX.

**Comment by rafaelks** [comment]
@antgel Is this still happening in 3.0?

**Comment by antgel** [comment]
@rafaelks Hey man, I don't see a 3.0 release. Did it happen?!?!

**Comment by rafaelks** [comment]
@antgel It's in BETA channel of Google Play, you need to sign up to receive the updates.

**Comment by antgel** [comment]
@rafaelks Thanks for the offer but I'd rather not, stability is important, it's mission-critical, and RC upgrades (not so much Android) have historically broken things from time to time. (I'm assuming the beta can't be installed in parallel with the last release...)

**Comment by localguru** [comment]
Can not confirm with 2.6.1.

**Comment by antgel** [comment]
@rafaelks It's still happening in 3.0.0, and 3.1.0 hasn't hit my Play Store yet (and I don't see the fix in the changelog).

**Comment by rafaelks** [comment]
@antgel 3.1.0 should be available for you now.

**Comment by antgel** [comment]
@rafaelks Still happening to me and to all our users.

**Comment by for7raid** [comment]
@rafaelks  Still happening in 3.3.1

**Comment by gigawhitlocks** [comment]
This bug single-handedly makes the Android client unusable. I have been telling my users to load our server in the mobile browser instead of attempting to use the app based on this bug alone.

Sometimes I use the app and after chatting for awhile the messages are all out of order, but I've noticed that if I rock my phone to landscape, they sort! So I just rock it back and forth every now and then.

**Comment by gigawhitlocks** [comment]
I put a bounty on this because it's driving me insane https://www.bountysource.com/issues/63360030-bug-the-last-message-jumps-over-the-first

**Comment by geekgonecrazy** [comment]
If you set phones time back say 10 minutes this can be reproduced 100% of the time.  

My guess is when sending it uses the phones created time stamp and even when it gets the confirmation it isn't updating the rendered time stamp.

If you rotate display or in any way cause a re-render of the message list it corrects its self.  I'm guessing because it has the correct time in the message database from the server.

This likely can be fixed by either grabbing the timestamp from the server when confirmation is received.. or establishing an offset to use with internal timestamps so closer to accurate.

A video of it happening can be found here: https://open.rocket.chat/channel/support?msg=5MZReTh2TtZjyGCDX

But confirmed can be reproduced super easy by just setting local time back.  Then have a real time conversation with someone.  It will happen almost instantly

**Comment by Shailesh351** [comment]
@gigawhitlocks @geekgonecrazy I went in depth of the issue.

This is what happening when new msg is sent,
a) Android stores it in local(which you can see in grey color)
b) Makes server api call
c) Gets result and updates local database

![Screenshot from 2019-05-23 13-36-33](https://user-images.githubusercontent.com/18264684/58236502-a9c36c80-7d60-11e9-950b-558ec440f0ef.png)

So in current implementation there are two bugs
1) When the android local system time is behind server time it puts msg in between previous msgs
Expected behaviour: It should put latest msg at the bottom
Solution: When sending msg we can take into consideration timestamp of last msg in the room. And set `max` of (`(timestamp of last msg)+1`  and `current time of local system`)

2) When updated msg comes from server at step `c` it is not updating position of it in the list
Expected behaviour: It should position updated msg correctly.

I'm submitting PR for it soon.
Thank you :smiley:

**Comment by philipbrito** [comment]
Closed by https://github.com/RocketChat/Rocket.Chat.Android/pull/2337

**Comment by gigawhitlocks** [comment]
Wow, merged without addressing any of the concerns brought up! What a waste of a $50 bounty. Last time I do that.

**Comment by gigawhitlocks** [comment]
This bug can almost certainly still be replicated if server time is behind mobile client time. The issue should remain open until tests are added to the testing suite to show that a positive or negative time delta between the client and server do not cause incorrect ordering of messages.
