### ISSUE TITLE
Turn Rocket Chat into a viral app, New features and improvements suggestions

### ISSUE THREAD

**Issue by FaizanZahid** [RocketChat/Rocket.Chat.Android#1833]
Guys, I love rocket chat, and i have tested it quite a while and here are my suggestions for you if you guys want to beat Slack.

1. Ability to list all online users like we can see in react native app.
2. Ability to record audio notes directly from the app itself.
3. Tapping a user anywhere on its username or pic should open that user's profile view with an option to DM them, like its done on react native and on messenger app by Facebook.
4. Ability to do video calls and audio calls from app itself like whatsapp to any user..
5. Show all files/attachments in a grid layout or newsfeed layout like facebook and perhaps allow the viewing user to tap a pic or message for long and then be able to reply to that file or add reaction to that file or image. Like its possible in the chatrooms view.
6. Add a social share option for files, such as tapping on it will allow Ability to share pics/files/videos externally with others like on messneger, whatsapp, email etc. Just like the 3 dot social icon we see on all apps these days. We should have a social share icon too, this will hugely increase rocket chat in getting viral.
7. Users profile view should allow users to add more info about them, for e.g, photo albums like instagram, short bio about them, a way to follow users or favorite them or star them, so that other users can star other users, and users can see who i m following and who is following me.
8. Allow a list /grid style newsfeed for all members like a general channel, where people can post anything, like a status and other people who are following those members can reply or like, just like facebook posts. This will turn rocket chat into a viral chat community, people will discuss stuff like they do on discourse.
9. When a a file is being viewed for e.g a video or image in full screen, allow users to swipe left or right, or show arrow buttons left or right to allow them to navigate to the next and previous pics/attachement , this will increase user retention time greatly. Right now we have to go back each time a full screen image is being shown, its not a good UX. And we have to tap on new image again from small thumbnail.

**Comment by rafaelks** [comment]
Thanks for your feedback @FaizanZahid! Let me try to answer to your points...

1. We didn't implement this feature in our app because we didn't find useful to see only the online users in the mobile app right now. Most of the users don't seem to really care about the status of the users when in mobile, they just initiate the conversations. But thanks for letting us know that this feature is important for you, we'll reconsider if it makes sense or not to include in the app;
2. Yes, this is already in our roadmap. Thanks for letting us know that you would like this feature;
3. Yes, this is already in our roadmap. Thanks for letting us know that you would like this feature;
4. Yes, we do have plans to integrate solutions like Jitsi into the app;
5. Great suggestion, thanks;
6. Sharing a file from other app into Rocket.Chat is also already in our roadmap (#98). Thanks for letting us know that you would like this feature;
7. We have plans to show more information about the user, but they're limited to what the user have in the database of Rocket.Chat. Currently there's a way to include custom fields to each user and we'll be showing it in the mobile apps. You can probably take advantage of it for your usage;
8. There are some discussions related to some kind of "Discovery" in Rocket.Chat but nothing concrete right now, thanks for you suggestion;
9. Thanks for you suggestion.

I'll be closing the issue since it includes many things in one. We'll be creating separated ones to each implementation.

Again, thanks for your feedback! 👍
