### ISSUE TITLE
[BUG] Multiple copies of message is being sent when one is expected

### ISSUE THREAD

**Issue by lorek123** [RocketChat/Rocket.Chat.Android#2008]
## Describe the bug
When user sends a message and hits multiple times send button, app will send last message multiple times. Users do this when application is not responding and not expecting to actually send it multiple times. 
## To Reproduce
1. Type a message
2. Smash the hell of the send button
3. See the multiple occurences of the last message

## Expected behavior
Only one occurence of message sent to server.

## Logs
Nothing in logs.

## Screenshots
![image](https://user-images.githubusercontent.com/1567272/51787038-1f317e80-216d-11e9-9a23-009f057bfe7c.png)

## Devices and Versions
Your Rocket.Chat.Android version:  3.2.0
Your Rocket.Chat Server version: 0.70.4
Mobile device model and OS version: Xiaomi Mi 5, LineageOS 15.1

**Comment by Pitstopper** [comment]
I confirm this problem.

**Comment by bkraul** [comment]
Same issue here. I would suppose it is not necessarily rate limiting what is needed but to disable the send button while the message is sending. Because what it seems happening is that the message is not being delivered causing the user to tap, and then you see 6-7 messages.

There is also another issue that happens as a result of this one. You try to delete the message, but in the Android app, it gets deleted, and then it comes right back (it does show gone on the web/electron app, though).

**Comment by bkraul** [comment]
Any updates on this? This appears to happen more when on mobile data. It pretty much renders the app unusable.

**Comment by bizzbyster** [comment]
As the steps to reproduce are written, I'm not able to make it happen. Maybe there's something I can do to exacerbate the problem so I can experience it?

**Comment by gigawhitlocks** [comment]
I suspect it appears more readily when the network connection from the client is not good. If you have a testing instance of RocketChat available, you could use the `tc` tool in Linux on that instance to simulate a shoddy connection to the listening port on the server.

**Comment by bizzbyster** [comment]
can you please test the fix I just posted? I did eventually reproduce it but it would be great if you could verify that the fix addresses what you are seeing as well. Thanks!

**Comment by gigawhitlocks** [comment]
Yes, I will test this fix ASAP, hopefully tonight.
