### ISSUE TITLE
How to run Rocket.Chat Native Android Application

### ISSUE THREAD

**Issue by rajitgarg2** [RocketChat/Rocket.Chat.Android#238]
Hello,

I have follow all the steps mention in this documentation for Rocket.Chat Native Android Application, and I am getting this message after all the steps.

BUILD SUCCESSFUL

https://github.com/RocketChat/Rocket.Chat.Android

Can anyone inform to me, now how i can create its apk

and also when i am running meteor command on this, then it is giving me error like this,

```
To create a new Meteor project:
  meteor create <project name>
```

Thanks a lot in advance

**Comment by laggedHero** [comment]
@rajitgarg2 There are two points here:

1 - Running the Rocket.Chat server: If you need help with that, you should go to the project repo (https://github.com/RocketChat/Rocket.Chat) or our docs (https://rocket.chat/docs/). This repository is for the native Android app.

2 - If you ran the `assembleDebug` Gradle command, your apk should be in the build directory of your app module. But, more important than that, I would recommend you to study Android development (Google has some training material here https://developer.android.com/training/index.html) in order to better cope with Android stuff.

I'll be closing this issue.

**Comment by rajitgarg2** [comment]
Thanks
