### ISSUE TITLE
Navigation "Back" [from channel] does not refresh unread counts/marks

### ISSUE THREAD

**Issue by exec228** [RocketChat/Rocket.Chat.Android#2435]
## Describe the bug
Unread marks are not refreshed when navigating "Back"

## To Reproduce
1. Go to main screen
2. See two/several channels in bold font as unread.
3. Tap on channel, read messages
4. See "red line of unread" not moved
5. Press "Back" button
6. See the same channels still in bold font as unread.

## Expected behavior
4.See "red line of unread" moved to bottom or whatever.
6.See read channels without unread marks, such as bold font etc.

Android 9, this rocket-chat {kotlin 3.5.0-2074}. Stable connection.
Rocket server 1.1.3 engine 1.4.2

## Additional details
Leave-and-enter app forcibly refreshes unread marks correctly.

Probably, navigation "Back" does not force refreshing of unread messages.

**Comment by mschmitzer** [comment]
Same problem
 * Android 8.1.0
 * App Version 3.5.0 from the Play Store
 * Server Version 1.1.3 (engine 1.4.2)

**Comment by twi123** [comment]
I think, in v3.4.2 this part works fine...

**Comment by for7raid** [comment]
the same in 3.5.0
3.5.1 not work at all

**Comment by twi123** [comment]
I think, its all related to redesigned [ConnectionManager](https://github.com/RocketChat/Rocket.Chat.Android/blob/v3.5.1/app/src/main/java/chat/rocket/android/server/infrastructure/ConnectionManager.kt) -- single [`launch` block](https://github.com/RocketChat/Rocket.Chat.Android/blob/v3.5.1/app/src/main/java/chat/rocket/android/server/infrastructure/ConnectionManager.kt#L129) instead of three.

Just replace this block with 
```
        launch {
            for (room in client.roomsChannel) {
                Timber.d("Got room streamed")
                roomsActor.send(room)
            }
        }
        launch {
            for (subscription in client.subscriptionsChannel) {
                Timber.d("Got subscription streamed")
                roomsActor.send(subscription)
            }
        }
        launch {
            for (user in client.activeUsersChannel) {
                userActor.send(user)
            }
        }
```
and try.  It works for me... :)
I'll try figure it out later...

**Comment by aenonGit** [comment]
> I think, its all related to redesigned [ConnectionManager](https://github.com/RocketChat/Rocket.Chat.Android/blob/v3.5.1/app/src/main/java/chat/rocket/android/server/infrastructure/ConnectionManager.kt) -- single [`launch` block](https://github.com/RocketChat/Rocket.Chat.Android/blob/v3.5.1/app/src/main/java/chat/rocket/android/server/infrastructure/ConnectionManager.kt#L129) instead of three.
> 
> Just replace this block with
> 
> ```
>         launch {
>             for (room in client.roomsChannel) {
>                 Timber.d("Got room streamed")
>                 roomsActor.send(room)
>             }
>         }
>         launch {
>             for (subscription in client.subscriptionsChannel) {
>                 Timber.d("Got subscription streamed")
>                 roomsActor.send(subscription)
>             }
>         }
>         launch {
>             for (user in client.activeUsersChannel) {
>                 userActor.send(user)
>             }
>         }
> ```
> 
> and try. It works for me... :)
> I'll try figure it out later...

tried and works like a charm. Besides it fixes also users' status in chatrooms list not being updated

but I can't explain why

**Comment by philipbrito** [comment]
@twi123 Good finding! Could you please send us a PR with that fix? Although creating multiples `launch` has a very very small impacts on the performance, this is really the way to go since we are listening to multiple channels - seems like it is not possible to have a single one where we have multiple streams this way. That's the explanation @aenonGit
