### ISSUE TITLE
Authentication error - connection error

### ISSUE THREAD

**Issue by JigneshWorld** [RocketChat/Rocket.Chat.Android#264]
Your Rocket.Chat.Android version: 1.0.10

Issue while exploring the app. 
- Sometimes in between I am getting issue like continues showing me authenticating & error.

Can anyone help/direct me to get started on understanding of related code and fix it if I can?

![screenshot_20170425-183952](https://cloud.githubusercontent.com/assets/7347854/25387248/cafa86f0-29e7-11e7-9d3a-f7958371f6df.png)
![screenshot_20170425-183933](https://cloud.githubusercontent.com/assets/7347854/25387241/c754862c-29e7-11e7-83e3-c2bc20917227.png)

**Comment by geekgonecrazy** [comment]
Yeah this is an issue where its having trouble establishing a websocket connection.  I think there might be an issue open for this already.  Its for sure known issue in the beta.  :+1:

**Comment by JigneshWorld** [comment]
Thanks for confirming. 
Does anyone in team working on this or I should start looking into this in detailed level?

Any help or direction will be appreciated. 👍

**Comment by geekgonecrazy** [comment]
@laggedHero would be able to better answer that.  I don't think so currently.  Feel free to dig in.   I'm not super familiar with the code base yet.  But i'd start by looking around in the websocket area.

**Comment by laggedHero** [comment]
@JigneshPatel23 There's no one in the team working on that right now. If you want to try it out, take a look on the `chat.rocket.android.service` package.

The network layer is really sensitive to network conditions. We could use some improvements!

**Comment by JigneshWorld** [comment]
Thanks for your insight it will help me a lot. 
I will dig on that part and try to understand the behaviour and issue in details.

**Comment by matheusjardimb** [comment]
Hi @JigneshPatel23, thanks for contributing!

As said before, we're dealing with some issues regarding the network layer. 
Also, as @geekgonecrazy mentioned, we already have another issue addressing this problem ( #268 )

I'd be great to have your help solving this issues. You may consider taking a look at `RxWebSocket.java` and  `chat.rocket.android.service` package.

That said, I'm closing this as duplicated of  #268 since both address the same problem (websocket instability)
