### ISSUE TITLE
[Question] Why not use React Native?

### ISSUE THREAD

**Issue by cyclops24** [RocketChat/Rocket.Chat.Android#270]
Hi,
I see this repo today and have some questions.
Why not using React Native?
I think with react native more people can contribute and we have a single code base between Android and iOS.

**Comment by cyclops24** [comment]
For example mattermost deprecate native version and start new react native version here:    https://github.com/mattermost/mattermost-mobile

**Comment by cyclops24** [comment]
If we switch to react native we can also use awesome tools like this:  
https://github.com/FaridSafi/react-native-gifted-chat

**Comment by rafaelks** [comment]
@cyclops24 Thanks for your question. That's actually a question everybody does when starting a new app. We do think that there's more contributors in the world that knows Java/Android than React Native right now. That's the main reason we choose using the native language instead of the using a 3rd part one.

Also, we do believe that developing native applications by using its native language are better in terms of receiving new features quickly, bug fixes, features in the development environment, etc.

That's our opinion right now, we are not "fixed" to it, so maybe in the future we want to change, or use both at the same time, like some big apps are doing today.

This answer is also true for our iOS native app, that's currently being developed in Swift, here: https://github.com/RocketChat/Rocket.Chat.iOS.

Thanks for asking!
