### ISSUE TITLE
Formatting and style are ruined

### ISSUE THREAD

**Issue by rabidang3ls** [RocketChat/Rocket.Chat.Android#289]
Your Rocket.Chat.Android version: 2.5.0 (Based on version in Play Store)

I was prompted in-app this morning for an update. After accepting the update, the app shows all content stacked on top of each other. I've tried restarting the app, and my phone with no success. I'm on Verizon with Samsung Galaxy S7 Edge.

![2017-05-17 13 11 49](https://cloud.githubusercontent.com/assets/2701664/26185627/5f865d86-3b49-11e7-83b7-7d1a7692c79c.png)

**Comment by geekgonecrazy** [comment]
Your issue is with https://github.com/rocketchat/rocket.chat.cordova

But go into Admin and layout make a small change in the color section and then stop the mobile app reopen and if prompts for an update.  Allow it.

If this doesn't work please open an issue on the other repo.  Make sure to list what you've tried :)
