### ISSUE TITLE
[INVESTIGATE] Remove retrolambda dependency

### ISSUE THREAD

**Issue by matheusjardimb** [RocketChat/Rocket.Chat.Android#313]
It has been recently released that Android will start having built-in support for Java 8 features therefore retrolambda should become unnecessary.

Vide: 
- https://youtu.be/rHiA66zUv8c?t=1m53s
- https://developer.android.com/studio/preview/features/java8-support.html

With that in mind, this issue must address proper investigation and changes in the code.

**Comment by rafaelks** [comment]
@filipedelimabrito How's the progress of this one?

**Comment by philipbrito** [comment]
This is not done yet because the [Android Studio 3](https://developer.android.com/studio/preview/index.html?hl=pt-br) is in beta at this moment. Lets wait until the AS 3 reaches a stable version.

Note: AS3 introduces a new Android Plugin, bringing breaking changes, like the new [dependency configurations](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#new_configurations)

**Comment by rafaelks** [comment]
Closing in this case.
