### ISSUE TITLE
Building Rocket.Chat Native Android Application

### ISSUE THREAD

**Issue by atikulhaider** [RocketChat/Rocket.Chat.Android#324]
Hi,
I have successfully installed Rocket.Chat on my CentOS 7 server. It is up & running nicely.
I want to build the Native Android app.
Although i'm Android newbie, I know I'm able to build it mysely if you please help me a bit :)
I have seen your instruction:

> Retrolambda needs java8 to be installed on your system

`export ANDROID_HOME=/path/to/android/sdk`

`git clone https://github.com/RocketChat/Rocket.Chat.Android.git`
`cd Rocket.Chat.Android`

`echo "sdk.dir="$ANDROID_HOME > local.properties`

`./gradlew assembleDebug`

But I don't understand where to start from. If you please help me with the commands to build it on Linux, it would be helpful. Just like some tutorial.
I don't understand this line too "Retrolambda needs java8 to be installed on your system".

**Comment by matheusjardimb** [comment]
Hi @atikulhaider, thanks for getting in touch!

Yep, there's some missing documentation, specially on this 'getting started' moment for new developers. We already have an open issue regarding missing documenation: #272
I'll close this issue and add your request on that one, as a new topic.

In order to solve your last question: 
- Retrolambda is the name of a dependency this app have
- It requires java8 installed in your environment in order to work properly
- Simply run `java -version` into your terminal and the result must be something like `java version "1.8.0_131"`. If that's not the case, you should make proper changes into your environment.
