### ISSUE TITLE
Unable to add Direct Messages

### ISSUE THREAD

**Issue by aenonGit** [RocketChat/Rocket.Chat.Android#326]
Your Rocket.Chat.Android version: latest

When you log into the chat it automatically populates the "RealmUser" class by calling the meteor/server/publications/activeUsers API. 

"Unfortunately" it only retrieves the "active users" thus if you try to add a new DM, the dialog only shows suggestions if the searched user is inside the RealmUser class. Hence it is not possible to add DM to offline users

**Comment by rafaelks** [comment]
@aenonGit This is a known issue, the `spotlight` method to search is only returning channels. Can you take a look on this @matheusjardimb?

Thanks @aenonGit!

**Comment by matheusjardimb** [comment]
@rafaelks not really sure how your comment relates to this issue :) 
The current implementation follows @aenonGit explanation: app loads all online users once the user logs in and the direct message search box only searches into stored users. 

You mean that I should use `spotlight` method instead of querying local db? I guess the app should start requesting more users from the server while the user is typing in the search box.

**Comment by rafaelks** [comment]
@matheusjardimb Oh yeah... my comment is "part" of the issue.

Few things:
1) Today when we search we should look first for the DB results;
2) If there's no DB results (or user press some kind of `See more results` button) we need to execute the `spotlight` socket method;
3) The response of the `spotlight` will have users and channels

Is that it?

**Comment by philipbrito** [comment]
Starting on [1.0.16](https://github.com/RocketChat/Rocket.Chat.Android/releases/tag/v1.0.16) version you can now search for any user from the Spotlight and start a new DM.
