### ISSUE TITLE
Investigate notifications reliability on Android

### ISSUE THREAD

**Issue by luciofm** [RocketChat/Rocket.Chat.Android#360]
Notifications seems to not be very reliable on Android. We also are using GCM which is deprecated now.

**Comment by philipbrito** [comment]
It is recommended to replace the GCM to FCM, although the GCM is not deprecated (yet).

From [GCM FAQ](https://developers.google.com/cloud-messaging/faq): 

> **Is GCM going to be deprecated?**
We will continue to support the current version of GCM Android and iOS SDKs because we know a lot of developers are using GCM SDKs today to handle notifications, and client app upgrade takes time.
But all new client-side features will be added to FCM SDKs only moving forward. You are strongly encouraged to upgrade to FCM SDKs.

So, give a feedback if updating the GCM version lib by the below PR solves your current problem.

Note: We are able to get notifications on Android 6 and Android 8, but obviously we need to test w/ our all supported versions.
