### ISSUE TITLE
[BUG] Channels not loaded correctly

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat.Android#470]
Your Rocket.Chat.Android version: 1.0.18

Mobile device model and OS version: Samsung S6 Android 7

After installing the app from the Play store the channels list is not loaded correctly. You only see a blank channel list.

**Comment by rafaelks** [comment]
@TheReal1604 I believe this is fixed in 1.0.20, can you try downloading the `Beta` from Google Play?

**Comment by antgel** [comment]
@rafaelks We're seeing something possibly related - when we go into channels, the content of the channels is empty. How can we access the beta? I don't see it in the Play Store. Better still, why not just release a version with the fix in? It's severe enough to make the app unusable. (Using Rocket.Chat 0.58.2, for what it's worth.)

**Comment by rafaelks** [comment]
@antgel To access Beta, you need to go to the Play Store page in the bottom of the screen and apply for Beta.

I see what you're saying... we never publish the app directly in Production, because it may have some unexpected crash in some Android version of specific device. We'll release 1.0.20 later this week to everyone. 👍

**Comment by rafaelks** [comment]
Closing this issue, not happening anymore.
