### ISSUE TITLE
[Question] RC React Native

### ISSUE THREAD

**Issue by mmarif4u** [RocketChat/Rocket.Chat.Android#672]
Was wondering, do RC team maintain this app too. Repo for it?

https://play.google.com/store/apps/details?id=chat.rocket.reactnative&hl=en

I thought the focus would be on native this[Rocket.Chat.Android] app.
In that case would not it be better to focus on one app?

**Comment by aniketsingh03** [comment]
@mmarif4u https://github.com/RocketChat/Rocket.Chat.ReactNative is the repo of react native app.

**Comment by mmarif4u** [comment]
@aniketsingh03 thanks for the link.

Still waiting for a proper answer to the many apps theory here.

**Comment by rafaelks** [comment]
@mmarif4u I understand the confusion with our apps. But let me try to make it more clear.

1. Our official apps, the ones that we recommend everybody fork if they want to customize and download to use, is our native apps. They're all called **Rocket.Chat+** in Google Play and App Store.

2. We do have a Cordova version of the app in App Store and Google Play+. This version is deprecated and should not be used to fork and customize;

3. Recently we also started a project using ReactNative technology. This isn't suppose to be our official app, but since we're an open source company, we thought that creating an app with such framework could have some impact in the community. The idea behind using this technology is to foment and see how the community respond to the efforts on the app;
