### ISSUE TITLE
[DOCS] Update documentation to include build details.

### ISSUE THREAD

**Issue by aniketsingh03** [RocketChat/Rocket.Chat.Android#731]
The present README.md does not contain details to build the v2.0.0 of the app.

**Comment by aniketsingh03** [comment]
@filipedelimabrito @leonardoaramaki can I work on this one?

**Comment by rafaelks** [comment]
@aniketsingh03 Yes, please! :-)

**Comment by aniketsingh03** [comment]
From where (master,develop) should I branch out to work on this one?

**Comment by philipbrito** [comment]
@aniketsingh03 From the `develop-2.x` branch since it is related to v2+ app.

**Comment by aniketsingh03** [comment]
I was thinking about adding details related to both versions, like the app is present in 2 versions, v1 maintained in `develop` branch and v2 maintained in `develop-2.x` branch. And then adding detailed info specific to the branch. What do you think @filipedelimabrito ?

**Comment by philipbrito** [comment]
You can do that but since we plan to merge the `develop-2.x` into `develop` it can waste time. `v1` is no longer maintained, `v2` lacks some functionality but it is better than the `v1`.
I'd like to recommend writing the build details for the `v2` and if you (really) have free time go to `v1` :smile:
