### ISSUE TITLE
Android app loads server but only displays blue screen

### ISSUE THREAD

**Issue by bukkits-** [RocketChat/Rocket.Chat.Android#8]
When server is connected, the android app only displays a blue screen with a small white box in the middle. Confirmation from other team members that this is what they see on connecting as well.

Looking at google play reviews, this seems to be an issue that others are having when attempting to use the app.

EDIT:
Additional information - 
App only connects with an http:// prefix. When using the demo server, the white box eventually expands to become the login screen. Could this be a problem with https:// and loading secure content?

**Comment by valessiobrito** [comment]
+1

I have the same problem;  Using 'http://my.domain'

![screenshot_2016-01-18-11-51-47](https://cloud.githubusercontent.com/assets/310049/12393402/94e4744a-bddc-11e5-96e6-141b9570d9ad.png)

**Comment by fduraibi** [comment]
I had this problem before, and I can confirm it is not related to http and https.  It is working with an old server I have over https.  But I migrated to a new server and it didn't work on the new server but still works with the old one.

So minuets ago I wanted to test it again. In the android app I had all three servers configured. My old and new servers plus the rocket chat demo server.
I deleted the old server record and while trying to add it again I entered the address of the new one by mistake!
It showed the little window about updating since files and it worked.

It didn't create another server record since it matched the existing one. But maybe that forced it to update our fix something. I deleted the new server record and added it again to test and it works still.

**Comment by Sing-Li** [comment]
If you have downloaded your app from the Android Playstore.  This is the wrong repo to report the problem.

This repo is for a not-yet-published, you must compile your own, version of a high performance native Android app.

Please report your problem here:

https://github.com/RocketChat/Rocket.Chat.Cordova

In addition - the above problem was due to a bug introduced by a testing version end of last week. If you used the release (stable) version of the server - it should not be a problem.
