### ISSUE TITLE
Android Keyboard pop up when entering a channel

### ISSUE THREAD

**Issue by cr22rc** [RocketChat/Rocket.Chat.Android#866]
Description:

Android Rocket.Chat 2.7.0 when I enter a channel the cursor is put in the message box. This seems to pop up the keyboard which is REALLY annoying since it then covers half the screen when all you want to do read messages first before you going to respond to anything. Always have to dismiss it.
This just started happening when our server got upgraded and I also was asked to download a new client.

BTW I have another user tell me they've seen this very behavior too so it's not just me.
This is on the Hyperledger fabric project.

Android 7.0
Server Setup Information:

Version of Rocket.Chat Server: 0.62.0
Operating System: Linux
Deployment Method(snap/docker/tar/etc): https://galaxy.ansible.com/RocketChat/Server/
Number of Running Instances: 1
DB Replicaset Oplog: mongodb://127.0.0.1:27017/rocketchat
Node Version: v8.9.4
mongoDB Version: mongodb-2.6.12-6.el7.x86_64
Steps to Reproduce:

just enter a channel
Expected behavior:

see all the messages without any keyboard showing up.
Actual behavior:

Cursor is in keyboard and half the screen is covered up :(

Other users have experienced this too. (I'm not alone here)

https://streamable.com/62nc2

May need to click on picture to play

**Comment by leonardoaramaki** [comment]
@cr22rc This is an issue from the Cordova app. Please open this issue on the Cordova repo: https://github.com/RocketChat/Rocket.Chat.Cordova

**Comment by lunitic** [comment]
@leonardoaramaki Same thing happens if you using chrome in Android. I would say reopen the issue.. It seems to be a general android thing. Probably a server side issue. Either this ticket or #10037 should be open

**Comment by leonardoaramaki** [comment]
@lunitic This issue is closed here because this repository is related to the Android native app. The one that the OP is using is the Android Cordova one.
This issue should be reported to https://github.com/rocketchat/Rocket.Chat.Cordova. Anyway, it's important to remark that the Cordova app is getting deprecated so I'd advise that you look for the Rocket.Chat.Android+ on Google Play (there you should subscribe to Beta to get the most recent updates) or even look for the RN if that suits you.
