### ISSUE TITLE
Reacting on messages does not work

### ISSUE THREAD

**Issue by ruKurz** [RocketChat/Rocket.Chat.Android#939]
Your Rocket.Chat.Android version: alpha1

Mobile device model and OS version: 6.0

1. Select a message and hold
2. Select 'react'
3. Choose an symbol
4. The dialog disapears but no icon is being displayed

**Comment by leonardoaramaki** [comment]
This is probably happening because currently the app works only online which means we're not storing things on disk just yet (db - only some things that we **need** to cache). That being said, although it's weighing on our roadmap to do soon, the app does not retry any failed jobs at this early alpha stage. What I think might have happened to you is that either the request for the reaction failed or the websocket failed to receive the update of the message getting reacted.
I apologize for this issue but we're rushing to have all the most important features done until the end of the month and personally, I hope to have the offline architecture already there, though not guaranteed.

**Comment by rafaelks** [comment]
@ruKurz What's the version of your server? Maybe you don't have the reaction APIs yet.

**Comment by ruKurz** [comment]
0.61

**Comment by rafaelks** [comment]
@ruKurz You'll have to use 0.62+ in order to use Reactions, can you try upgrading it please? I'm gonna close this one for now.
